"""added_reset_password_fields

Revision ID: 49310668d0e9
Revises: 43874eb91c11
Create Date: 2025-07-03 20:04:19.864287

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49310668d0e9'
down_revision: Union[str, None] = '43874eb91c11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('reset_password_email_token', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('users', sa.Column('resetPasswordExpirationTime', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_users_reset_password_email_token'), 'users', ['reset_password_email_token'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_reset_password_email_token'), table_name='users')
    op.drop_column('users', 'resetPasswordExpirationTime')
    op.drop_column('users', 'reset_password_email_token')
    # ### end Alembic commands ###
